---
- name: set epicodus permission for /System/Library/User Template
  file: path="/System/Library/User Template" owner=epicodus recurse=yes

- name: create /usr/local directory
  file: path=/usr/local state=directory

- name: install homebrew
  shell: curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C /usr/local

- name: set epicodus permission for /usr/local
  file: path=/usr/local recurse=yes owner=epicodus

- name: create /opt directory with epicodus permission
  file: path=/opt state=directory owner=epicodus recurse=yes

- name: create /opt/gem directory
  file: path=/opt/gem state=directory

# NOT FOR NEW MACHINES
# - name: give epicodus permission for /Library/Caches/Homebrew
#   file: path=/Library/Caches/Homebrew owner=epicodus recurse=yes
