---
- hosts: epicodus_test
  vars:
    guest_path: /System/Library/User Template/English.lproj
    dot_files:
      - bash_profile
      - gemrc
      - git_pairs
      - gitconfig
      - gitignore_global
      - railsrc
      - rspec
    homebrew_packages:
      - git
      - heroku-toolbelt
      - brew-cask
      - ruby
      - postgres
      - node
      - watchman
      - composer
      - drush
      - httpd24
      - mysql
      - phpmyadmin
      - gradle
      - javarepl
    homebrew_taps:
      - homebrew/dupes
      - homebrew/versions
      - homebrew/php
      - homebrew/apache
      - caskroom/cask
    gems:
      - bundler
      - simple-git-pair
    guest_account:
      - auto_login_guest.mobileconfig
      - login_window.mobileconfig
    npm_packages:
      - bower
      - ember-cli
    other_files:
      - meraki_agent.pkg
    plists:
      - de.appsolute.MAMP.plist # MAMP preferences, suppress MAMP PRO prompt
      - com.apple.Terminal.plist # Terminal preferences
    profiles:
      - meraki_sm_mdm.mobileconfig
      - dock.mobileconfig
      - energy_saver.mobileconfig
      - keyboard_mapping.mobileconfig
      - suppress_icloud_assistant.mobileconfig
  roles:
    - role: setup
    - role: config_files
    - { role: blockinfile, become: yes }
    - dependencies
    - dot_files
    - app_settings
    - role: guest_permissions
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
    PGDATA: "/System/Library/User Template/English.lproj/.postgres"
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
