---
- hosts: epicodus_west
  roles:
    - { role: root_setup, become: yes }
    - dot_files
    - { role: blockinfile, become: yes }
    - dependencies
    - pre-commit
    - postgres
    - { role: guest_permissions, become: yes }
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
    PGDATA: "/System/Library/User Template/English.lproj/.postgres"
