---
- hosts: epicodus_test
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
    COMPOSER_HOME: "{{ guest_path }}/.composer"
    PGDATA: "/System/Library/User Template/English.lproj/.postgres"
  roles:
    - { role: yaegashi.blockinfile, become: yes }
    - setup
    - other
    - ruby
    - javascript
    - php
    - java
    - app_settings
    - guest_permissions
  vars:
    guest_path: /System/Library/User Template/English.lproj
    java_homebrew_taps:
      - caskroom/cask
    java_homebrew_dependencies:
      - brew-cask
      - gradle
      - javarepl
    javascript_homebrew_dependencies:
      - node
      - watchman
    javascript_npm_packages:
      - bower
      - ember-cli
    other_files:
      - bash_profile
      - gitconfig
      - gitignore_global
    other_homebrew_dependencies:
      - git
      - heroku-toolbelt
    php_homebrew_dependencies:
      - { name: 'httpd24', options: '' }
      - { name: 'php56', options: 'with-homebrew-apxs' }
      - { name: 'composer', options: '' }
      - { name: 'mysql', options: '' }
      - { name: 'phpmyadmin', options: '' }
    php_homebrew_taps:
      - homebrew/dupes
      - homebrew/versions
      - homebrew/php
      - homebrew/apache
    ruby_files:
      - gemrc
      - railsrc
      - rspec
    ruby_homebrew_dependencies:
      - ruby
      - postgres
    ruby_gems:
      - bundler
      - pivotal_git_scripts
    setup_guest_account:
      - auto_login_guest.mobileconfig
      - login_window.mobileconfig
    setup_profiles:
      - dock.mobileconfig
      - energy_saver.mobileconfig
      - keyboard_mapping.mobileconfig
      - suppress_icloud_assistant.mobileconfig
