---
- name: install other dependencies
  homebrew: name={{ item }}
  with_items:
    - "{{ other_homebrew_dependencies }}"

- name: copy dot files
  copy: src={{ item }} dest="{{ guest_path }}/.{{ item }}"
  with_items:
    - "{{ other_files }}"

- name: copy pre-commit
  copy: src=pre-commit dest=/usr/local/share/git-core/templates/hooks/pre-commit

- name: change permissions for pre-commit
  file: path=/usr/local/share/git-core/templates/hooks/pre-commit mode=0755
