---
- name: copy meraki_sm_mdm.mobileconfig
  copy: src=meraki_sm_mdm.mobileconfig dest=~/Desktop/meraki_sm_mdm.mobileconfig

- name: install meraki_sm_mdm.mobileconfig
  shell: profiles -I -F /Users/epicodus/Desktop/meraki_sm_mdm.mobileconfig
  sudo: yes

- name: remove meraki_sm_mdm.mobileconfig
  shell: rm /Users/epicodus/Desktop/meraki_sm_mdm.mobileconfig

- name: remove MerakiSM-Agent-epicodus.pkg
  shell: rm /Users/Guest/Desktop/MerakiSM-Agent-epicodus.pkg
  sudo: yes
