---
- name: copy profiles
  copy: src={{ item }} dest=/Users/epicodus/{{ item }}
  with_items:
    - "{{ profiles }}"

- name: copy plists
  copy: src={{ item }} dest="{{ guest_path }}/Library/Preferences/{{ item }}"
  sudo: yes
  with_items:
    - "{{ plists }}"

- name: install profiles
  shell: profiles -I -F /Users/epicodus/{{ item }}
  sudo: yes
  with_items:
    - "{{ profiles }}"

- name: remove profiles
  file: path=/Users/epicodus/{{ item }} state=absent
  with_items:
    - "{{ profiles }}"
