---
- name: java homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - "{{ java_homebrew_taps }}"

- name: install brew-cask
  homebrew: name=brew-cask

- name: install java
  homebrew_cask: name=java
  become: yes

- name: install java dependencies
  homebrew: name={{ item }}
  with_items:
    - "{{ java_homebrew_dependencies }}"

# STUDENTS
- name: make AndroidStudio2.1 directory
  file: path="{{ guest_path }}/Library/Preferences/AndroidStudio2.1" state=directory
  when: "'students' in group_names"

- name: set permissions for /Users/Shared/Android
  file: path="/Users/Shared/Android" owner=Guest recurse=yes mode=a+rwx state=directory
  become: yes
  when: "'students' in group_names"

- name: make options directory
  file: path="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options" state=directory
  when: "'students' in group_names"

- name: copy ide.general.xml
  copy: src=ide_general dest="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options/ide.general.xml"
  when: "'students' in group_names"

- name: copy jdk.table.xml
  copy: src=jdk_table dest="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options/jdk.table.xml"
  when: "'students' in group_names"

- name: copy project.default.xml
  copy: src=project_default dest="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options/project.default.xml"
  when: "'students' in group_names"

- name: copy updates.xml
  copy: src=updates dest="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options/updates.xml"
  when: "'students' in group_names"

- name: copy options.xml
  copy: src=options dest="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options/options.xml"
  when: "'students' in group_names"

- name: copy androidStudioFirstRun.xml
  copy: src=first_run dest="{{ guest_path }}/Library/Preferences/AndroidStudio2.1/options/androidStudioFirstRun.xml"
  when: "'students' in group_names"
# STUDENTS

# STAFF
- name: make AndroidStudio2.1 directory
  file: path="{{ staff_path }}/Library/Preferences/AndroidStudio2.1" state=directory
  become: yes
  when: "'staff' in group_names"

- name: set permissions for /Users/Shared/Android
  file: path="/Users/Shared/Android" owner=epicodus_staff recurse=yes mode=a+rwx state=directory
  become: yes
  when: "'staff' in group_names"

- name: set permissions for AndroidStudio2.1 directory
  file: path="{{ staff_path }}/Library/Preferences/AndroidStudio2.1" owner=epicodus_staff recurse=yes mode=a+rwx state=directory
  become: yes
  when: "'staff' in group_names"

- name: make options directory
  file: path="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options" state=directory
  become: yes
  when: "'staff' in group_names"

- name: copy ide.general.xml
  copy: src=ide_general dest="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options/ide.general.xml"
  become: yes
  when: "'staff' in group_names"

- name: copy jdk.table.xml
  copy: src=jdk_table dest="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options/jdk.table.xml"
  become: yes
  when: "'staff' in group_names"

- name: copy project.default.xml
  copy: src=project_default dest="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options/project.default.xml"
  become: yes
  when: "'staff' in group_names"

- name: copy updates.xml
  copy: src=updates dest="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options/updates.xml"
  become: yes
  when: "'staff' in group_names"

- name: copy options.xml
  copy: src=options dest="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options/options.xml"
  become: yes
  when: "'staff' in group_names"

- name: copy androidStudioFirstRun.xml
  copy: src=first_run dest="{{ staff_path }}/Library/Preferences/AndroidStudio2.1/options/androidStudioFirstRun.xml"
  become: yes
  when: "'staff' in group_names"
# STAFF
