---
- name: set epicodus permission for /System/Library/User Template
  file: path="/System/Library/User Template" owner=epicodus recurse=yes
  sudo: yes

- name: create /usr/local directory
  file: path=/usr/local state=directory
  sudo: yes

- name: check if homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_installed

- name: install homebrew
  shell: curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C /usr/local
  sudo: yes
  when: homebrew_installed.stat.exists == false

- name: set epicodus permission for /usr/local
  file: path=/usr/local recurse=yes owner=epicodus state=directory
  sudo: yes

- name: create /opt directory with epicodus permission
  file: path=/opt state=directory owner=epicodus recurse=yes
  sudo: yes

- name: create /opt/gem directory
  file: path=/opt/gem state=directory
  sudo: yes

# GUEST ACCOUNT
- name: copy Guest account profiles
  copy: src={{ item }} dest=/Users/epicodus/{{ item }}
  with_items:
    - "{{ guest_account }}"

- name: install Guest account profiles
  shell: profiles -I -F /Users/epicodus/{{ item }}
  sudo: yes
  with_items:
    - "{{ guest_account }}"

- name: remove Guest account profiles
  file: path=/Users/epicodus/{{ item }} state=absent
  with_items:
    - "{{ guest_account }}"

- name: copy daemon plist that disables Guest user MCX restrictions
  copy: src=com.davincid.disable-guest-mcx-restrictions.plist dest=/Library/LaunchDaemons/com.davincid.disable-guest-mcx-restrictions.plist
  sudo: yes
