---
- name: set epicodus permission for /Library/Caches/Homebrew
  file: path=/Library/Caches/Homebrew owner=epicodus recurse=yes state=directory
  sudo: yes

- name: set epicodus permission for /System/Library/User Template
  file: path="/System/Library/User Template" owner=epicodus recurse=yes
  sudo: yes

- name: check if homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_installed

- name: install homebrew
  shell: curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C /usr/local
  sudo: yes
  when: homebrew_installed.stat.exists == false

- name: set epicodus permission for /usr/local
  file: path=/usr/local recurse=yes owner=epicodus state=directory
  sudo: yes

# GUEST ACCOUNT
- name: copy Guest account profiles
  copy: src={{ item }} dest=/Users/epicodus/{{ item }}
  with_items:
    - "{{ setup_guest_account }}"

- name: install Guest account profiles
  shell: profiles -I -F /Users/epicodus/{{ item }}
  sudo: yes
  with_items:
    - "{{ setup_guest_account }}"

- name: remove Guest account profiles
  file: path=/Users/epicodus/{{ item }} state=absent
  with_items:
    - "{{ setup_guest_account }}"

- name: remove restrictions for Guest account
  shell: dscl . -mcxdelete /Users/Guest && rm -rf /Library/Managed\ Preferences/Guest
  sudo: yes
# GUEST ACCOUNT

- name: copy profiles
  copy: src={{ item }} dest=/Users/epicodus/{{ item }}
  with_items:
    - "{{ setup_profiles }}"

- name: copy Terminal preferences plist
  copy: src=com.apple.Terminal.plist dest="{{ guest_path }}/Library/Preferences/com.apple.Terminal.plist"
  sudo: yes

- name: install profiles
  shell: profiles -I -F /Users/epicodus/{{ item }}
  sudo: yes
  with_items:
    - "{{ setup_profiles }}"

- name: remove profiles
  file: path=/Users/epicodus/{{ item }} state=absent
  with_items:
    - "{{ setup_profiles }}"
