---
- name: set epicodus permission for /Library/Caches/Homebrew
  file: path=/Library/Caches/Homebrew owner=epicodus recurse=yes state=directory
  sudo: yes
  when: "'students' in group_names"

- name: set epicodus permission for /System/Library/User Template
  file: path="/System/Library/User Template" owner=epicodus recurse=yes
  sudo: yes
  when: "'students' in group_names"

- name: check if homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_installed

- name: install homebrew
  shell: curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C /usr/local
  sudo: yes
  when: homebrew_installed.stat.exists == false

- name: set epicodus permission for /usr/local
  file: path=/usr/local recurse=yes owner=epicodus state=directory
  sudo: yes
  when: "'students' in group_names"

# GUEST ACCOUNT
- name: copy Guest profiles
  copy: src={{ item }} dest=/Users/epicodus/{{ item }}
  with_items:
    - "{{ setup_guest_account }}"
  when: "'students' in group_names"

- name: install Guest profiles
  shell: profiles -I -F /Users/epicodus/{{ item }}
  sudo: yes
  with_items:
    - "{{ setup_guest_account }}"
  when: "'students' in group_names"

- name: remove Guest profiles
  file: path=/Users/epicodus/{{ item }} state=absent
  with_items:
    - "{{ setup_guest_account }}"
  when: "'students' in group_names"

- name: remove restrictions for Guest
  shell: /usr/bin/dscl . -mcxdelete /Users/Guest && rm -rf "/Library/Managed Preferences/Guest"
  sudo: yes
  when: "'students' in group_names"
# GUEST ACCOUNT

- name: copy profiles
  copy: src={{ item }} dest=/Users/epicodus/{{ item }}
  with_items:
    - "{{ setup_profiles }}"

- name: copy dock profile for staff
  copy: src=staff_dock.mobileconfig dest=/Users/epicodus/staff_dock.mobileconfig
  when: "'staff' in group_names"

- name: copy Terminal preferences plist
  copy: src=com.apple.Terminal.plist dest="{{ guest_path }}/Library/Preferences/com.apple.Terminal.plist"
  sudo: yes

- name: install profiles for Guest
  shell: profiles -I -F /Users/epicodus/{{ item }}
  sudo: yes
  with_items:
    - "{{ setup_profiles }}"
  when: "'students' in group_names"

- name: install keyboard mapping preferences for staff
  shell: profiles -I -F /Users/epicodus/keyboard_mapping.mobileconfig
  sudo: yes
  when: "'staff' in group_names"

- name: install dock profile for staff
  shell: profiles -I -F /Users/epicodus/staff_dock.mobileconfig
  sudo: yes
  when: "'staff' in group_names"

- name: remove dock profile for staff
  file: path=/Users/epicodus/staff_dock.mobileconfig state=absent

- name: remove profiles
  file: path=/Users/epicodus/{{ item }} state=absent
  with_items:
    - "{{ setup_profiles }}"

- name: get staff username
  shell: whoami
  register: remote_username
  when: "'staff' in group_names"

- name: set staff permission for /usr/local
  file: path=/usr/local recurse=yes owner={{ remote_username.stdout }} state=directory
  sudo: yes
  when: "'staff' in group_names"
