---
- name: php homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - "{{ php_homebrew_taps }}"

- name: install php dependencies
  homebrew: name={{ item }}
  with_items:
    - "{{ php_homebrew_dependencies }}"

# STUDENTS
- name: copy MAMP preferences plist for Guest
  copy: src=de.appsolute.MAMP.plist dest="{{ guest_path }}/Library/Preferences/de.appsolute.MAMP.plist"
  become: yes
  when: "'students' in group_names"

- name: check if drush is installed for Guest
  stat: path="{{ guest_path }}/.composer/vendor/drush"
  register: drush_installed_guest
  when: "'students' in group_names"
  environment:
    COMPOSER_HOME: "{{ guest_path }}/.composer"

- name: install drush for Guest
  shell: /usr/local/bin/composer global require drush/drush:7.* -n --prefer-source
  when: "'students' in group_names and drush_installed_guest.stat.exists == false"
  environment:
    COMPOSER_HOME: "{{ guest_path }}/.composer"

- name: set Guest permission for /Applications/MAMP
  file: path=/Applications/MAMP owner=Guest recurse=yes
  become: yes
  when: "'students' in group_names"
# STUDENTS

# STAFF
- name: copy MAMP preferences plist for staff
  copy: src=de.appsolute.MAMP.plist dest="{{ staff_path }}/Library/Preferences/de.appsolute.MAMP.plist"
  become: yes
  when: "'staff' in group_names"

- name: check if drush is installed for staff
  stat: path="{{ staff_path }}/.composer/vendor/drush"
  register: drush_installed_staff
  when: "'staff' in group_names"
  environment:
    COMPOSER_HOME: "{{ staff_path }}/.composer"

- name: install drush for staff
  shell: /usr/local/bin/composer global require drush/drush:7.* -n --prefer-source
  when: "'staff' in group_names and drush_installed_staff.stat.exists == false"
  environment:
    COMPOSER_HOME: "{{ staff_path }}/.composer"

- name: set staff permission for /Applications/MAMP
  file: path=/Applications/MAMP owner=epicodus_staff recurse=yes
  become: yes
  when: "'staff' in group_names"
# STAFF
