---
- name: homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - "{{ homebrew_taps }}"

- name: install php56
  homebrew: name=php56 install_options=homebrew-apxs

- name: install homebrew packages
  homebrew: name={{ item }}
  with_items:
    - "{{ homebrew_packages }}"

- name: install java
  homebrew_cask: name=java
  sudo: yes

- name: install gems
  gem: name={{ item }}
  with_items:
    - "{{ gems }}"

- name: install npm packages
  npm: name={{ item }} global=yes state=latest
  with_items:
    - "{{ npm_packages }}"

# POSTGRES
- name: remove existing postgres cluster
  file: path="{{ guest_path }}/.postgres" state=absent force=yes

- name: initialize postgres cluster
  shell: pg_ctl init

- name: start postgres
  shell: pg_ctl start

- name: create Guest database
  shell: createdb Guest

- name: create Guest superuser
  shell: createuser -s Guest

- name: stop postgres
  shell: pg_ctl stop
# POSTGRES

# MYSQL
- name: start mysql server
  shell: mysql.server start

- name: set mysql root password
  shell: mysqladmin -u root password root

- name: stop mysql server
  shell: mysql.server stop
# MYSQL
