---
- name: update and upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - "{{ homebrew_taps }}"

- name: uninstall homebrew packages
  homebrew: name={{ item }} state=absent
  with_items:
    - "{{ homebrew_uninstall }}"

- name: install php56
  homebrew: name=php56 install_options=homebrew-apxs

- name: install homebrew packages
  homebrew: name={{ item }}
  with_items:
    - "{{ homebrew_packages }}"

- name: install java
  homebrew_cask: name=java
  sudo: yes

# - name: install homebrew_cask packages
#   homebrew_cask: name={{ item }}
#   with_items:
#     - "{{ homebrew_casks }}"

- name: install gems
  gem: name={{ item }}
  with_items:
    - "{{ gems }}"

- name: install npm packages
  npm: name={{ item }} global=yes state=latest
  with_items:
    - "{{ npm_packages }}"

# Postgres
- name: remove existing postgres cluster
  file: path="/System/Library/User Template/English.lproj/.postgres" state=absent force=yes

- name: initialize postgres cluster
  shell: pg_ctl init

- name: start postgres
  shell: pg_ctl start

- name: create Guest database
  shell: createdb Guest

- name: create Guest superuser
  shell: createuser -s Guest

- name: stop postgres
  shell: pg_ctl stop

# - name: install php56, httpd24, mysql, phpmyadmin
#   shell: brew install httpd24 php56 --homebrew-apxs mysql phpmyadmin

- name: start mysql server
  shell: mysql.server start

# - name: set mysql root password
#   shell: mysqladmin -u root password root

- name: stop mysql server
  shell: mysql.server stop
