---
# NOT FOR NEW MACHINES
# - name: brew doctor
#   shell: brew doctor
#
# - name: updates homebrew itself
#   homebrew: update_homebrew=yes
#
# - name: upgrades all homebrew packages
#   homebrew: upgrade_all=yes
#
# - name: clean up homebrew
#   shell: brew cleanup
#
# - name: prune homebrew
#   shell: brew prune
#
# - name: update all npm packages
#   shell: npm update -g


- name: taps homebrew/dupes
  homebrew_tap: tap=homebrew/dupes

- name: taps homebrew/versions
  homebrew_tap: tap=homebrew/versions

- name: taps homebrew/php
  homebrew_tap: tap=homebrew/php

- name: taps homebrew/apache
  homebrew_tap: tap=homebrew/apache

- name: install git
  homebrew: name=git

- name: install heroku-toolbelt
  homebrew: name=heroku-toolbelt

- name: install postgres
  homebrew: name=postgres

- name: install ruby
  homebrew: name=ruby

- name: install php56, httpd24, mysql, phpmyadmin
  shell: brew install httpd24 php56 --homebrew-apxs mysql phpmyadmin

- name: install composer
  homebrew: name=composer

- name: install drush
  homebrew: name=drush

- name: install node
  homebrew: name=node

- name: install watchman
  homebrew: name=watchman

- name: install bundler
  shell: gem install bundler

- name: install simple-git-pair
  shell: gem install simple-git-pair

- name: install bower
  npm: name=bower global=yes state=latest

- name: install ember-cli
  npm: name=ember-cli global=yes state=latest
