---
- name: install ruby dependencies
  homebrew: name={{ item }}
  with_items:
    - "{{ ruby_homebrew_dependencies }}"

- name: install ruby gems
  gem: name={{ item }}
  with_items:
    - "{{ ruby_gems }}"

- name: remove existing postgres cluster
  file: path=/usr/local/var/postgres state=absent force=yes

- name: initialize postgres cluster
  shell: pg_ctl init

- name: start postgres
  shell: pg_ctl start

# STUDENTS
- name: create Guest database
  shell: createdb Guest
  when: "'students' in group_names"

- name: create Guest superuser
  shell: createuser -s Guest
  when: "'students' in group_names"

- name: copy ruby files for Guest
  copy: src={{ item }} dest="{{ guest_path }}/.{{ item }}"
  with_items:
    - "{{ ruby_files }}"
  when: "'students' in group_names"
# STUDENTS

# STAFF
- name: create staff database
  shell: createdb placeholder
  when: "'staff' in group_names"

- name: create staff superuser
  shell: createuser -s placeholder
  when: "'staff' in group_names"

- name: copy ruby files for staff
  copy: src={{ item }} dest="{{ staff_path }}/.{{ item }}"
  with_items:
    - "{{ ruby_files }}"
  when: "'staff' in group_names"
# STAFF

- name: stop postgres
  shell: pg_ctl stop
